### ISSUE TITLE
Automatically quit edit mode

### ISSUE THREAD

**Issue by philacs** [spsdco/notes#165]
This happens randomly, sometimes it's fine, sometimes after I double click and entered editing mode, it will quit to display mode within 2 seconds.

springseed 2.0 on ubuntu 12.04 x64

**Comment by nitishch** [comment]
The same situation happened to me. I think the problem is with Dropbox sync. Everytime the app attempts to sync the notes, it exits edit mode. Try switching off the sync (If you want to sync your notes, enable sync, wait for some time and then disable sync). Ideally, this is not how behaviour should be but this is the only solution I could come up with.

**Comment by thakurvijendar** [comment]
same problem here guys...
is there any solution for this
else i'm thinking of going back to springseed 1.1

**Comment by melamity** [comment]
#210 will outline the next version of Springseed - 2.x right now (since being written 2 years ago) is a little unsalvageable
